export { default as Loading } from './loading/Loading';
export { default as Signin } from './Signin/Signin';
export { default as Home } from './Home/Home';
export { default as Header } from './Header/Header';
export { default as Sidebar } from './Sidebar/Sidebar';
export { default as Compose } from './compose/Compose';
export { default as Main } from './Main/Main';
export { default as Mail } from './Mail/Mail';
export { default as SimpleSnackbar} from './Snackbar/Snackbar';
export { default as ViewMail } from './ViewMail/ViewMail';